version: "3.2"

# networks:
#   app:
#     driver: bridge
 
services: 
  client:
    container_name: "client"
    build:
      context: ./frontend
    # volumes:
      # - ./frontend:/srv/client/
      # - "/srv/client/node_modules" 
    expose:
      - "3000" 

  app:
    container_name: "backend"
    build:
      context: ./backend
    volumes:
      - static_volume:/srv/app/.static
      - ./backend/.media:/srv/app/.media
      - ./backend:/srv/app/
    restart: always
    expose:
      - "8000"
    depends_on:
      - client
  
  nginx:
    container_name: "nginx"
    image: nginx:latest
    volumes:
      - static_volume:/srv/app/.static
      - ./backend/.media:/srv/app/.media 
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    # networks:
    #   - app
    depends_on:
      - app
      - client

volumes:
  static_volume:
  client_volume:
  
