version: '3'

# networks:
#   app:
#     driver: bridge
 
services:
  app:
  
  client: 
  
  nginx:
    volumes:
      - ./nginx/nginx-release.conf:/etc/nginx/conf.d/default.conf  

volumes:
  static_volume:
  client_volume:
  
