version: "3.2"

# networks:
#   app:
#     driver: bridge

services:
  client:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/srv/client/src
      - ./frontend/public:/srv/client/public

  app:
    build:
      context: ./backend
    volumes:
      - static_volume:/srv/app/.static
      - ./backend/.media:/srv/app/.media
    restart: always
    expose:
      - "8000"
    depends_on:
      - client
      - database

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/srv/app/.static
      - ./backend/.media:/srv/app/.media
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    # networks:
    #   - app
    depends_on:
      - app
      - client
      
  database:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "13306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.mysql/:/var/lib/mysql/

volumes:
  static_volume: null
