version: '3'

# networks:
#   app:
#     driver: bridge
 
services:
  app:
    build:
      context: ./backend
    volumes:
      - static_volume:/srv/app/.static
      - media_volume:/srv/app/.media
    # command: >
    #   bash -c "
    #     python3 manage.py collectstatic &&
    #     gunicorn -c gunicorn.conf.py
    #   "
    # networks:
    #   - app
    expose:
      - "8000"

  client:
    build:
      context: ./frontend
    volumes:
      - client_volume:/srv/client
    depends_on:
      - app
    expose:
      - "8000" 
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - client_volume:/srv/client
      - static_volume:/srv/app/.static
      - media_volume:/srv/app/.media
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    # networks:
    #   - app
    depends_on:
      - app

volumes:
  static_volume:
  media_volume:
  client_volume:
  
