version: '3'

# networks:
#   app:
#     driver: bridge
 
services:
  app:
    container_name: "backend"
    build:
      context: ./backend
    volumes:
      - static_volume:/srv/app/.static
      - ./backend/.media:/srv/app/.media
      - ./backend:/srv/app/
    expose:
      - "8000"
    command: "python3 manage.py runserver 0:8000"

  client:
    container_name: "client"
    build:
      context: ./frontend
    volumes:
      - ./frontend:/srv/client
    depends_on:
      - app
    expose:
      - "8000" 
    command: "npm run start"
  
  nginx:
    container_name: "nginx"
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/srv/app/.static
      - ./backend/.media:/srv/app/.media
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    # networks:
    #   - app
    depends_on:
      - app

volumes:
  static_volume:
  client_volume:
  
